#name: Publish docs via GitHub Pages
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    name: Deploy docs
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout main
#        uses: actions/checkout@v3
#
#      - name: Deploy docs
#        uses: mhausenblas/mkdocs-deploy-gh-pages@master
#        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          # CUSTOM_DOMAIN: optionaldomain.com
#          CONFIG_FILE: ./mkdocs.yml
#          EXTRA_PACKAGES: build-base
#          # GITHUB_DOMAIN: github.myenterprise.com
#          REQUIREMENTS: folder/requirements.txt

name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          mkdocs gh-deploy

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
